---
# Doesnt work anymore, wkhtml don't provide debs for new versions
- include: 'deb.yml'
  when: false
- include: 'static.yml'

- apt: pkg=xvfb
  name: 'Wkhtmltox | Install Xvfb'
- include: 'font.yml'
  when: '{{wkhtmltox_install_fonts}}'



